/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class markusjx_cppjslib_nt_CppJsLibNative */

#ifndef _Included_markusjx_cppjslib_nt_CppJsLibNative
#define _Included_markusjx_cppjslib_nt_CppJsLibNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    initWebGUI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_initWebGUI__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    initWebGUI
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_initWebGUI__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jstring, jstring, jint);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    running
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_running
  (JNIEnv *, jclass, jint);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    stopped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_stopped
  (JNIEnv *, jclass, jint);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    checkPorts
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_checkPorts__IZ
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    checkPorts
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_checkPorts__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    setLogger
 * Signature: (ILmarkusjx/cppjslib/interfaces/LoggingFunction;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_setLogger__ILmarkusjx_cppjslib_interfaces_LoggingFunction_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    setError
 * Signature: (ILmarkusjx/cppjslib/interfaces/LoggingFunction;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_setError__ILmarkusjx_cppjslib_interfaces_LoggingFunction_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    setLogger
 * Signature: (Lmarkusjx/cppjslib/interfaces/LoggingFunction;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_setLogger__Lmarkusjx_cppjslib_interfaces_LoggingFunction_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    setError
 * Signature: (Lmarkusjx/cppjslib/interfaces/LoggingFunction;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_setError__Lmarkusjx_cppjslib_interfaces_LoggingFunction_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    setWebSocketOpenHandler
 * Signature: (ILmarkusjx/cppjslib/interfaces/Handler;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_setWebSocketOpenHandler
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    setWebSocketCloseHandler
 * Signature: (ILmarkusjx/cppjslib/interfaces/Handler;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_setWebSocketCloseHandler
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    start
 * Signature: (IIILjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_start
  (JNIEnv *, jclass, jint, jint, jint, jstring, jboolean);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    stop
 * Signature: (IZI)Z
 */
JNIEXPORT jboolean JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_stop
  (JNIEnv *, jclass, jint, jboolean, jint);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    exposeFunction
 * Signature: (ILmarkusjx/cppjslib/interfaces/CExposedFunc;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_exposeFunction
  (JNIEnv *, jclass, jint, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    exposeVoidFunction
 * Signature: (ILmarkusjx/cppjslib/interfaces/CExposedVoidFunc;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_exposeVoidFunction
  (JNIEnv *, jclass, jint, jobject, jstring, jobjectArray);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    importFunction
 * Signature: (ILjava/lang/String;Ljava/lang/String;[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_importFunction
  (JNIEnv *, jclass, jint, jstring, jstring, jobjectArray, jint);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    callJSFunction
 * Signature: (II[Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_callJSFunction
  (JNIEnv *, jclass, jint, jint, jobjectArray);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    callVoidJsFunction
 * Signature: (II[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_callVoidJsFunction
  (JNIEnv *, jclass, jint, jint, jobjectArray);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    stringArrayToJSON
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_stringArrayToJSON
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    createStringArrayFromJSON
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_createStringArrayFromJSON
  (JNIEnv *, jclass, jstring);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    deleteWebGUI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_deleteWebGUI
  (JNIEnv *, jclass, jint);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    ok
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_ok
  (JNIEnv *, jclass);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     markusjx_cppjslib_nt_CppJsLibNative
 * Method:    resetLastError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_markusjx_cppjslib_nt_CppJsLibNative_resetLastError
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
