name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: create include
      run: mkdir include
    - name: get json
      uses: wei/wget@v1
      with:
        args: -O include\json.hpp https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug .
    - name: build
      run: cmake --build .
