name: C/C++ CI

on:
  push:
    paths-ignore: 
      - "README.md"
      - "LICENSE"
      - "CppJsLibJs/**"
      - ".gitignore"
      - ".github/workflows/release.yml"
      - ".github/workflows/javabinding.yml"

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: create include
      run: mkdir include
    - name: get json
      uses: wei/wget@v1.1.1
      with:
        args: -O include/json.hpp https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp
    - name: get httplib
      uses: wei/wget@v1.1.1
      with:
        args: -O include/httplib.h https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_DLL=TRUE .
    - name: build
      run: cmake --build . 
    - name: run test
      shell: bash
      working-directory: ./test
      run: ./Test
    - name: Upload object
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibLinux
        path: src/libCppJsLib.so
    - name: Upload test
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibLinuxTest
        path: test
        
  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: create include
      run: mkdir include
    - name: get json
      shell: powershell
      run: wget https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp -OutFile include/json.hpp
    - name: get httplib
      shell: powershell
      run: wget https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h -OutFile include/httplib.h
    - name: cmake
      run: cmake -DUSE_DLL=TRUE .
    - name: build
      run: cmake --build .
    #- name: run test
    #  shell: cmd
    #  run: Test.exe
    #  working-directory: ./test/Debug
    - name: Upload library
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibWin
        path: src/Debug
    - name: Upload test
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibWinTest
        path: test/Debug
  
  build-macos:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: create include
      run: mkdir include
    - name: get json
      run: wget -O include/json.hpp https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp
    - name: get httplib
      run: wget -O include/httplib.h https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_DLL=TRUE .
    - name: build
      run: cmake --build .
    - name: run test
      run: ./Test
      shell: bash
      working-directory: ./test
    - name: Upload object
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibMacOs
        path: src/libCppJsLib.dylib
    - name: Upload test
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibMacOsTest
        path: test
  
  build-ubuntu-release:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: create include
      run: mkdir include
    - name: install boost
      run: sudo apt-get install libboost1.65-all-dev -y
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_HTTPS=TRUE -DENABLE_WEBSOCKET=TRUE -DBUILDDLL=TRUE .
    - name: build
      run: cmake --build . 
    #- name: run test
    #  run: ./Test
    #  shell: bash
    #  working-directory: ./test
    - name: Upload object
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibReleaseLinux
        path: src/libCppJsLib.so
    #- name: Upload test
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: CppJsLibReleaseLinuxTest
    #    path: test

  build-windows-release:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: create include folder
        run: mkdir include
      - name: create lib folder
        run: mkdir lib
      - name: download openssl
        shell: powershell
        run: wget https://www.npcglib.org/~stathis/downloads/openssl-1.1.0f-vs2017.7z -OutFile openssl.7z
      - name: unzip openssl
        run: 7z x openssl.7z -r -y
      - name: copy openssl headers
        run: cp -r openssl-1.1.0f-vs2017/include64/openssl include
        shell: cmd
      - name: copy openssl libs
        run: cp -r openssl-1.1.0f-vs2017/lib64/. lib
        shell: cmd
      - name: Install Boost
        run: choco install -y boost-msvc-14.1
      - name: run cmake
        run: cmake -DENABLE_HTTPS=TRUE -DENABLE_WEBSOCKET=TRUE -DBUILDDLL=TRUE .
        env:
          BOOST_ROOT: C:/local/boost_1_67_0
      - name: build
        run: cmake --build . --config Release
      #- name: copy libcrypto to src folder
      #  run: cp openssl-1.1.0f-vs2017/bin64/libcryptoMD.dll src/Release/libcryptoMD.dll
      #- name: copy libssl to src folder
      #  run: cp openssl-1.1.0f-vs2017/bin64/libsslMD.dll src/Release/libsslMD.dll
      #- name: copy libcrypto to test folder
      #  run: cp openssl-1.1.0f-vs2017/bin64/libcryptoMD.dll test/Release/libcryptoMD.dll
      #- name: copy libssl to test folder
      #  run: cp openssl-1.1.0f-vs2017/bin64/libsslMD.dll test/Release/libsslMD.dll
      #- name: run test
      #  run: Test.exe
      #  shell: cmd
      #  working-directory: ./test/Release
      - name: Upload library
        uses: actions/upload-artifact@v1
        with:
          name: CppJsLibReleaseWinOpenssl
          path: src/Release
      #- name: Upload test
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: CppJsLibReleaseWinTestOpenssl
      #    path: test/Release

  build-macos-release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: create include
      run: mkdir include
    - name: install boost
      run: brew install boost@1.60
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_HTTPS=TRUE -DENABLE_WEBSOCKET=TRUE -DBUILDDLL=TRUE -DBOOST_ROOT="/usr/local/opt/boost@1.60" .
    - name: build
      run: cmake --build .
    #- name: run test
    #  run: ./Test
    #  shell: bash
    #  working-directory: ./test
    - name: Upload object
      uses: actions/upload-artifact@v1
      with:
        name: CppJsLibReleaseMacOs
        path: src/libCppJsLib.dylib
    #- name: Upload test
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: CppJsLibReleaseMacOsTest
    #    path: test
