name: C/C++ CI

on:
  push:
    paths-ignore: 
      - "README.md"
      - "LICENSE"
      - "CppJsLibJs.js"
      - ".gitignore"
      - ".github/workflows/release.yml"
      - ".github/workflows/codeql-analysis.yml"

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        #os: [ ubuntu-latest, windows-latest, macOs-latest ]
         os: [ ubuntu-latest, macOs-latest ]
         options: [ openssl, boost, all, none ]

    steps:
    - uses: actions/checkout@v1

    # Install boost on every system
    - name: install boost ubuntu
      run: sudo apt-get install libboost-dev -y
      if: matrix.os == 'ubuntu-latest' && (matrix.options == 'boost' || matrix.options == 'all')
    - name: install boost macOs
      run: brew install boost
      if: matrix.os == 'macOs-latest' && (matrix.options == 'boost' || matrix.options == 'all')
    - name: install boost windows
      if: matrix.os == 'windows-latest' && (matrix.options == 'boost' || matrix.options == 'all')
      uses: MarkusJx/install-boost@v1.0
      id: install-boost
      with:
        boost_version: 1.71.0
        toolset: msvc14.2

    # Install openssl
    - name: install openssl macOs
      run: brew install openssl
      if: matrix.os == 'macOs-latest' && (matrix.options == 'openssl' || matrix.options == 'all')
    - name: install openssl windows
      run: choco install openssl -y
      if: matrix.os == 'windows-latest' && (matrix.options == 'openssl' || matrix.options == 'all')

    # Run cmake configure
    - name: cmake windows
      run: cmake . -B build
      if: matrix.os == 'windows-latest'
      env:
        BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}
    - name: cmake not windows
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} . -B build
      if: matrix.os != 'windows-latest'

    # Build
    - name: build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
    #- name: run test
    #  shell: bash
    #  working-directory: ./test
    #  run: ./Test
